### PR TITLE
Updated to Release 1.3.0.0

### PR DESCRIPTION
**Pull request by mayur-agarwal-lrn**
Added/Updated all the missing changes done till version 1.3.0.0 from the original repository (RusticiSoftware/TinCan.NET).
I have compared all the commits after this fork was created and incorporated all the required changes. Please review and merge.
Cheers :)

### CODE REVIEW

**Comment by mayur-agarwal-lrn** [comment]
All old and new unit test cases are passing.

**Comment by mayur-agarwal-lrn** [comment]
@njvsvalhalla  if you merge this, can you make sure we get an updated nuget package for this. That would be helpful. Thanks.

**Review by jagadeesh-dumpeta — APPROVED** [review]
Code changes looks fine.

**Comment by njvsvalhalla** [comment]
I'm going to update the repository tonight for everything but the csrpoj changes, and not the apache license file (that is already in the file LICENSE)

**Comment by matthieume** [comment]
Any update?

**Comment by mayur-agarwal-lrn** [comment]
Stale

**Pull request closed without merging**
